### PR TITLE
Update use of startsWith function to build with Qt 5.10

### PR DESCRIPTION
**Pull request by Vascom**
Changes to solve #373

### CODE REVIEW

File: eiskaltdcpp-qt/src/FinishedTransfers.h [hunk 1]
```diff
@@ -387,7 +387,7 @@ friend class dcpp::Singleton< FinishedTransfers<isUpload> >;
     }
 
     void openFile(QString file){
-        if (!file.startsWith("/"))
+        if (!file.startsWith(QString("/")))
```
Comment (tehnick) [inline eiskaltdcpp-qt/src/FinishedTransfers.h]: Why not QChar? It should work a bit faster.

Comment (Vascom) [reply eiskaltdcpp-qt/src/FinishedTransfers.h]: It not work with QChar
eiskaltdcpp-qt/src/FinishedTransfers.h:508:34: error: no matching function for call to 'QChar(const char [2])'
                 if (f.startsWith(QChar("/")))
                                  ^~~~~~~~~~

Comment (pavel-pimenov) [reply eiskaltdcpp-qt/src/FinishedTransfers.h]: QChar("/") -> QChar('/');

Comment (pavel-pimenov) [reply eiskaltdcpp-qt/src/FinishedTransfers.h]: or f.startsWith('/')

Comment (Vascom) [reply eiskaltdcpp-qt/src/FinishedTransfers.h]: OK. It work with QChar('/'). Pull request updated.

Comment (Vascom) [reply eiskaltdcpp-qt/src/FinishedTransfers.h]: @pavel-pimenov It not work with startsWith('/')

Comment (tehnick) [reply eiskaltdcpp-qt/src/FinishedTransfers.h]: > or f.startsWith('/')

It will not work due to ambiguous which constructor to use and which function to call.

**Comment by tehnick** [comment]
Merged. Thanks!
