### ISSUE TITLE
GTK port broken in master. fixeable or deprecated?

### ISSUE THREAD

**Issue by sl1pkn07** [eiskaltdcpp/eiskaltdcpp#399]
Hi, master can't build GTK port

is fixeable in future or the GTK port is deprecated?

greetings

**Comment by sl1pkn07** [comment]
~~~
[ 87%] Building CXX object eiskaltdcpp-gtk/CMakeFiles/eiskaltdcpp-gtk.dir/src/privatemessage.cc.o
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc: In constructor 'PrivateMessage::PrivateMessage(const string&, const string&)':
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:55:61: warning: 'void gtk_widget_override_font(GtkWidget*, const PangoFontDescription*)' is deprecated [-Wdeprecated-declarations]
         gtk_widget_override_font(getWidget("text"), fontDesc);
                                                             ^
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/entry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/bookentry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.hh:25,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:21:
/usr/include/gtk-3.0/gtk/gtkwidget.h:1153:14: note: declared here
 void         gtk_widget_override_font             (GtkWidget                  *widget,
              ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:55:61: warning: 'void gtk_widget_override_font(GtkWidget*, const PangoFontDescription*)' is deprecated [-Wdeprecated-declarations]
         gtk_widget_override_font(getWidget("text"), fontDesc);
                                                             ^
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/entry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/bookentry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.hh:25,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:21:
/usr/include/gtk-3.0/gtk/gtkwidget.h:1153:14: note: declared here
 void         gtk_widget_override_font             (GtkWidget                  *widget,
              ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc: In member function 'void PrivateMessage::updateCursor(GtkWidget*)':
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:800:124: warning: 'GdkDeviceManager* gdk_display_get_device_manager(GdkDisplay*)' is deprecated: Use 'gdk_display_get_default_seat' instead [-Wdeprecated-declarations]
     GdkDeviceManager *device_manager = gdk_display_get_device_manager(gdk_window_get_display(gtk_widget_get_window(widget)));
                                                                                                                            ^
In file included from /usr/include/gtk-3.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/entry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/bookentry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.hh:25,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:21:
/usr/include/gtk-3.0/gdk/gdkdisplay.h:171:20: note: declared here
 GdkDeviceManager * gdk_display_get_device_manager (GdkDisplay *display);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:800:124: warning: 'GdkDeviceManager* gdk_display_get_device_manager(GdkDisplay*)' is deprecated: Use 'gdk_display_get_default_seat' instead [-Wdeprecated-declarations]
     GdkDeviceManager *device_manager = gdk_display_get_device_manager(gdk_window_get_display(gtk_widget_get_window(widget)));
                                                                                                                            ^
In file included from /usr/include/gtk-3.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/entry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/bookentry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.hh:25,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:21:
/usr/include/gtk-3.0/gdk/gdkdisplay.h:171:20: note: declared here
 GdkDeviceManager * gdk_display_get_device_manager (GdkDisplay *display);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:801:79: warning: 'GdkDevice* gdk_device_manager_get_client_pointer(GdkDeviceManager*)' is deprecated [-Wdeprecated-declarations]
     GdkDevice *pointer = gdk_device_manager_get_client_pointer (device_manager);
                                                                               ^
In file included from /usr/include/gtk-3.0/gdk/gdkdisplay.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/entry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/bookentry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.hh:25,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:21:
/usr/include/gtk-3.0/gdk/gdkdevicemanager.h:44:14: note: declared here
 GdkDevice *  gdk_device_manager_get_client_pointer (GdkDeviceManager *device_manager);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:801:79: warning: 'GdkDevice* gdk_device_manager_get_client_pointer(GdkDeviceManager*)' is deprecated [-Wdeprecated-declarations]
     GdkDevice *pointer = gdk_device_manager_get_client_pointer (device_manager);
                                                                               ^
In file included from /usr/include/gtk-3.0/gdk/gdkdisplay.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/entry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/bookentry.hh:23,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.hh:25,
                 from /tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:21:
/usr/include/gtk-3.0/gdk/gdkdevicemanager.h:44:14: note: declared here
 GdkDevice *  gdk_device_manager_get_client_pointer (GdkDeviceManager *device_manager);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc: In static member function 'static gboolean PrivateMessage::onChatCommandButtonRelease_gui(GtkWidget*, GdkEventButton*, gpointer)':
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:1380:78: error: 'widget' was not declared in this scope
         gtk_menu_popup_at_widget(GTK_MENU(pm->getWidget("chatCommandsMenu")),widget,GDK_GRAVITY_SOUTH_WEST,GDK_GRAVITY_NORTH_WEST,NULL);
                                                                              ^~~~~~
/tmp/makepkg/eiskaltdcpp-git/src/eiskaltdcpp/eiskaltdcpp-gtk/src/privatemessage.cc:1380:78: note: suggested alternative: 'linger'
         gtk_menu_popup_at_widget(GTK_MENU(pm->getWidget("chatCommandsMenu")),widget,GDK_GRAVITY_SOUTH_WEST,GDK_GRAVITY_NORTH_WEST,NULL);
                                                                              ^~~~~~
                                                                              linger
make[2]: *** [eiskaltdcpp-gtk/CMakeFiles/eiskaltdcpp-gtk.dir/build.make:310: eiskaltdcpp-gtk/CMakeFiles/eiskaltdcpp-gtk.dir/src/privatemessage.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:460: eiskaltdcpp-gtk/CMakeFiles/eiskaltdcpp-gtk.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

~~~

**Comment by sl1pkn07** [comment]
3.24.8 (https://www.archlinux.org/packages/extra/x86_64/gtk3/)

**Comment by tehnick** [comment]
Do you compile program without any additional patches?

I have just rechecked build with GTK+ 3.24.5 in my system and program was built fine. Unfortunately, I cannot check build with GTK+ 3.24.8 now, but I'll look at changes in GTK+ which may lead to build error.

**Comment by sl1pkn07** [comment]
~~~
cd build
  cmake ../eiskaltdcpp \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DUSE_QT5=ON \
    -DUSE_QT_QML=OFF \
    -DUSE_QT_SQLITE=ON \
    -DUSE_GTK3=ON \
    -DLUA_SCRIPT=ON \
    -DUSE_MINIUPNP=ON \
    -DUSE_ASPELL=ON \
    -DUSE_LIBNOTIFY=ON \
    -DWITH_LUASCRIPTS=ON \
    -DWITH_SOUNDS=ON \
    -DWITH_DEV_FILES=ON \
    -DUSE_JS=ON \
    -DXMLRPC_DAEMON=OFF \
    -DPERL_REGEX=ON \
    -DENABLE_STACKTRACE=ON \
    -DJSONRPC_DAEMON=ON \
    -DUSE_CLI_XMLRPC=OFF \
    -DUSE_CLI_JSONRPC=ON \
    -DLOCAL_JSONCPP=OFF \
    -DLOCAL_BOOST=OFF
~~~

zero external patches except this sed line

~~~
  # Fix php dependency
  find . -type f -name '*.php' -exec sed 's|php5|php|g' -i '{}' \;
~~~

**Comment by tehnick** [comment]
> -DLOCAL_JSONCPP=OFF \

Hmm, does it really work and without segfaults in eiskaltdcpp-daemon?

> ` find . -type f -name '*.php' -exec sed 's|php5|php|g' -i '{}' \;`

But why?

```
$ grep -r php5 * --exclude-dir=builddir 
data/examples/commands.ru_RU.UTF-8.php:* $ sudo apt-get install php5-cli
data/examples/xmms2_audacious2.ru_RU.UTF-8.php:* Depends: php5, xmms2 | audacious2
eiskaltdcpp-qt/qtscripts/gnome/commands.ru_RU.UTF-8.php:* $ sudo apt-get install php5-cli
INSTALL:php5-cli (or other version, check the compatibility by yourself)
```

**Comment by tehnick** [comment]
> I have just rechecked build with GTK+ 3.24.5 in my system and program was built fine.

Sorry, I have mixed up ssh shells and tested build with 3.18.9. With GTK+ 3.24.5 you build error is reproducible. I'll fix it soon.

**Comment by sl1pkn07** [comment]
>Hmm, does it really work and without segfaults in eiskaltdcpp-daemon?

IDK, i only able to build with distro packages instead of bundled ones. at the moment, nobody reports problems about it

for reference., arch uses jsoncpp 1.8.4


>but why?

because archlinux use php 7.3.4 in their repos

~~~
└───╼  yaourt -Qi php 
Nombre                    : php 
Versión                   : 7.3.4-2
~~~

use php 5 require install php5x (exists almost 3 different versions (5.3.x, 5.5.x and 5.6.x) from [AUR] (user repository, ,maintained by the users, not arch devs)

greetings

**Comment by tehnick** [comment]
> IDK, i only able to build with distro packages instead of bundled ones.

```
ldd /usr/bin/eiskaltdcpp-daemon | grep -i json
```

> because archlinux use php 7.3.4 in their repos

php5 is not used in any `*.php` script. I have shown you a proof. This `sed` command does nothing...

**Comment by sl1pkn07** [comment]
>php5 no se utiliza en ningún *.phpscript. Te mostró una prueba. Este sedcomando no tiene nada ...

oh, my first notice. that line I used since 2015, since then, i never checked if the seebang is had been updated

**Comment by tehnick** [comment]
> only do to able *. sorry, I misspelled (post edited)

Sorry, I do not understand what you are sorry about... =)

Please show me output of command:
```
ldd /usr/bin/eiskaltdcpp-daemon | grep -i json
```
To be sure that system json libraries are really used.

**Comment by sl1pkn07** [comment]
~~~
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/eiskaltdcpp-git]|
└───╼  ldd /usr/bin/eiskaltdcpp-daemon | grep -i json
        libjsoncpp.so.20 => /usr/lib/libjsoncpp.so.20 (0x00007f42ec0cb000)
~~~

**Comment by sl1pkn07** [comment]
thanks for the fix!

greetings

**Comment by tehnick** [comment]
> at the moment, nobody reports problems about it
> `libjsoncpp.so.20 => /usr/lib/libjsoncpp.so.20 (0x00007f42ec0cb000)`

Probably this is because nobody uses eiskaltdcpp-daemon now. Or library was fixed...

BTW, as for eiskaltdcpp-gtk I suggest people to build it with GTK+ 2.24.x: it is works more stable than builds with GTK+ 3.x...
