### ISSUE TITLE
Error build with Qt >= 5.10.0

### ISSUE THREAD

**Issue by Vascom** [eiskaltdcpp/eiskaltdcpp#373]
```
/builddir/build/BUILD/eiskaltdcpp-eiskaltdcpp-4c9cbf2/eiskaltdcpp-qt/src/FinishedTransfers.h:390:33: error: call of overloaded 'startsWith(const char [2])' is ambiguous
         if (!file.startsWith("/"))
                                 ^
```
Full build log https://kojipkgs.fedoraproject.org//work/tasks/6976/24786976/build.log
Other components and versions https://kojipkgs.fedoraproject.org//work/tasks/6976/24786976/root.log

This can be because new GCC version or fresh Qt version.

Please help solve this problem to build eiskaltdcpp for Fedora.

**Comment by pavel-pimenov** [comment]
file.startsWith("/") ->file.startsWith('/') ?

**Comment by Vascom** [comment]
No. Same error https://kojipkgs.fedoraproject.org//work/tasks/1443/24791443/build.log

**Comment by Vascom** [comment]
May be it because startsWith function changed in Qt 5.10.

**Comment by tehnick** [comment]
> May be it because startsWith function changed in Qt 5.10.

https://doc.qt.io/qt-5/qstring.html#endsWith-2

> Please help solve this problem to build eiskaltdcpp for Fedora.

You may try something like:
```file.startsWith(QChar('/'))```
or
```file.startsWith(QStringLiteral("/"))```

**Comment by Vascom** [comment]
It work with
`sed -i 's|startsWith("/")|startsWith(QString("/"))|' eiskaltdcpp-qt/src/FinishedTransfers.h`

**Comment by pavel-pimenov** [comment]
@Vascom https://www.viva64.com/en/w/v817

**Comment by Vascom** [comment]
Pull request #374 updated.

**Comment by tehnick** [comment]
6ca065bd1952b431abe34f1fd8c5c16f81bd7262
